### ISSUE TITLE
Support for :em :i :strong :b

### ISSUE THREAD

**Issue by saintx** [markwoodhall/marge#1]
Support for `:em`, `:i`, `:strong`, and `:b` elements would be very helpful, as they are often supported in markdown as **strong** and *emphasis* elements.

**Comment by markwoodhall** [comment]
Thanks for raising this. It should be possible with 0.14.0 to do the following:

```clojure
(marge/markdown
 [:strong "Strong!"])
```

**Strong!**


```clojure
(marge/markdown
 [:em "Emphasised!"])
```

*Emphasised!*
